import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import org.antlr.v4.runtime.CharStreams;
import java.io.IOException;

import static jdk.internal.org.jline.utils.Log.error;

public class main {

	public static void main(String[] args) throws IOException {

		// we expect exactly one argument: the name of the input file
		if (args.length!=1) {
			System.err.println("\n");
			System.err.println("Impl Interpreter\n");
			System.err.println("=================\n\n");
			System.err.println("Please give as input argument a filename\n");
			System.exit(-1);
		}
		String filename=args[0];

		// open the input file
		CharStream input = CharStreams.fromFileName(filename);
		//new ANTLRFileStream (filename); // depricated

		// create a lexer/scanner
		implLexer lex = new implLexer(input);

		// get the stream of tokens from the scanner
		CommonTokenStream tokens = new CommonTokenStream(lex);

		// create a parser
		implParser parser = new implParser(tokens);

		// and parse anything from the grammar for "start"
		ParseTree parseTree = parser.start();

		// Construct an interpreter and run it on the parse tree
		Interpreter interpreter = new Interpreter();
		Double result=interpreter.visit(parseTree);
		System.out.println("The result is: "+result);
	}
}

// We write an interpreter that implements interface
// "implVisitor<T>" that is automatically generated by ANTLR
// This is parameterized over a return type "<T>" which is in our case
// simply a Integer.

class Interpreter extends AbstractParseTreeVisitor<Double> implements implVisitor<Double> {
	public Double visitStart(implParser.StartContext ctx){
		for(implParser.StartContext a:ctx.as){
			visit(a);
		}
		return visit(ctx);
	};
	@Override
	public Double visitLatchdec(implParser.LatchdecContext ctx) {
		return visitLatchdec(ctx);
	}

	@Override
	public Double visitUpdateDecl(implParser.UpdateDeclContext ctx) {
		return visitUpdateDecl(ctx);
	}

	@Override
	public Double visitSimInp(implParser.SimInpContext ctx) {
		return visitSimInp(ctx);
	}

	@Override
	public Double visitParenthesis(implParser.ParenthesisContext ctx) {
		return visit(ctx.expr());
	}

	@Override
	public Double visitMulDiv(implParser.MulDivContext ctx) {
		if(ctx.op.getText().equals("*")){
			return visit(ctx.expr(0))*visit(ctx.expr(1));}
		else return visit(ctx.expr(0))/visit(ctx.expr(1));
	};

	@Override
	public Double visitAddSub(implParser.AddSubContext ctx) {
		if(ctx.op.getText().equals("+"))
			return visit(ctx.e1)+visit(ctx.e2);
		else return visit(ctx.e1)-visit(ctx.e2);
	};


	@Override
	public Double visitALPHA3(implParser.ALPHA3Context ctx) {
		return visitALPHA3(ctx);
	}

	@Override
	public Double visitALPHA2(implParser.ALPHA2Context ctx) {
		return visitALPHA2(ctx);
	}

	@Override
	public Double visitALPHA1(implParser.ALPHA1Context ctx) {
		return visitALPHA1(ctx);
	}

	@Override
	public Double visitEXPR1(implParser.EXPR1Context ctx) {
		error("This function should not be called actually");
		return null;
	}

	@Override
	public Double visitAND(implParser.ANDContext ctx) {
		if (ctx.an.getText().equals("&&")) {
			if((visit(ctx.c1)==1.0)&&(visit(ctx.c2)==1.0)){
				return 1.0;
			} else {
				return 0.0;
			}
		}
		return 0.0;
	}
	@Override
	public Double visitOR(implParser.ORContext ctx) {
		if (ctx.or.getText().equals("||")) {
			if((visit(ctx.c1)==1.0)||(visit(ctx.c2)==1.0)){
				return 1.0;
			} else
				return 0.0;
		}
		return 0.0;
	}

	@Override
	public Double visitEXPR3(implParser.EXPR3Context ctx) {
		error("This function should not be called actually");
		return null;
	}

	@Override
	public Double visitEXPR4(implParser.EXPR4Context ctx) {
		error("This function should not be called actually");
		return null;
	}

	@Override
	public Double visitEXPR5(implParser.EXPR5Context ctx) {
		error("This function should not be called actually");
		return null;
	}
}

